// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_APIKEY']!,
    appId: dotenv.env['FIREBASE_WEB_APPID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGINGSENDERID']!,
    projectId: dotenv.env['FIREBASE_PROJECTID']!,
    authDomain: dotenv.env['FIREBASE_WEB_AUTHDOMAIN']!,
    storageBucket: dotenv.env['FIREBASE_STORAGEBUCKET']!,
    measurementId: dotenv.env['FIREBASE_WEB_MEASUREMENTID']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_APIKEY']!,
    appId: dotenv.env['FIREBASE_ANDROID_APPID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGINGSENDERID']!,
    projectId: dotenv.env['FIREBASE_PROJECTID']!,
    storageBucket: dotenv.env['FIREBASE_STORAGEBUCKET']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_APIKEY']!,
    appId: dotenv.env['FIREBASE_IOS_APPID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGINGSENDERID']!,
    projectId: dotenv.env['FIREBASE_PROJECTID']!,
    storageBucket: dotenv.env['FIREBASE_STORAGEBUCKET']!,
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENTID']!,
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLEID']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_APIKEY']!,
    appId: dotenv.env['FIREBASE_IOS_APPID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGINGSENDERID']!,
    projectId: dotenv.env['FIREBASE_PROJECTID']!,
    storageBucket: dotenv.env['FIREBASE_STORAGEBUCKET']!,
    iosClientId: dotenv.env['FIREBASE_IOS_CLIENTID']!,
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLEID']!,
  );
}
